INSERT INTO ships (name, manufacturer,shipClass, size, isUnique, slug) VALUES
('A Wing','Kuat Systems Engineering','interceptor',7,'no','a-wing'),
('AA-9 Coruscant Freighter','Botajef Shipyards','Freighter',390, 'no','aa-9-coruscant-freighter'),
('Acclamator Assault Ship','Rothana Heavy Engineering','Cruiser - Heavy',460,'no','acclamator-assault-ship'),
('Agressor Assault Bomber','Trilon','Starfighter',20,'no','agressor-assault-bomber'),
('Agressor Class Destroyer','Galactic Empire','Destroyer',1500,'no','agressor-destroyer'),
('Arquiten','Kuat Drive Yards','Cruiser - Light',325,'no','arquiten'),
('Atmostphere Assault Lander','Sienar-Jaemus Army Systems','Transport',17,'no','atmostphere-assault-lander'),
('B Wing','Slayn & Korpil','Starfighter',17,'no','b-wing'),
('B7','Loronar Corporation','Freighter',19,'no','b7'),
('Baleen Heavy Freighter','Correllian Engineering Corporation','Freighter',459,'no','baleen-heavy-freighter'),
('Battle Dragon','Olanji-Charubah','Cruiser - Medium',500,'no','battle-dragon'),
('Belarus','Loronar Corporation','Cruiser - Medium',400,'No','belarus'),
('Bespin Twin Pod Cloud Car','Bespin Motors','Patrol Ship',7,'no','bespin-twin-pod-cloud car'),
('Carrack Cruiser','Damorian Manufacturing Corporation','Cruiser - Light',350,'no','carrack-cruiser'),
('Centerpoint Station','Killik','Station',350000,'yes','centerpoint-station'),
('Chu`unthor','Republic Fleet Systems','Cruiser - Medium',2000,'yes','chu-unthor'),
('Cloakshape fighter','Kuat Systems Engineering','Starfighter',15,'no','coakshape-fighter'),
('Consular Cruiser','Correllian Engineering Corporation','Transport',115,'no','consular-cruiser'),
('Corona Frigate','Kuat Drive Yards','Frigate',275,'No','corona-frigate'),
('Coronet','Kalevala Spaceworks','Luxury Space Yacht',216,'yes','coronet'),
('CR 90','Correllian Engineering Corporation','Corvette',150,'no','cr-90'),
('Crusader','Mandal Motors','Corvette',80,'No','crusader'),
('Death Star','Galactic Empire','Super Weapon',160000,'yes','death-star'),
('Death Star II','Galactic Empire','Super Weapon',200000,'yes','death-star-ii'),
('Delta 7 Starfighter','Kuat Systems Engineering','Starfighter',8,'no','delta-7'),
('Dooku Solar Sailer','Huppla Pasa Tisc','Yacht',15,'yes','dooku-solar-sailer'),
('Dreadnaught','Rendili StarDrive','Battleship',600,'no','dreadnaught'),
('E Wing','Freitek','Starfighter',11,'no','e-wing'),
('Ebon Hawk','Core Galaxy Systems','Freighter',24,'yes','ebon-hawk'),
('Eclipse Star Destoyer','Kuat Drive Yards','Dreadnaught',17500,'Yes','eclipse-star-destoyer'),
('Enforcer One','Core Galaxy Systems','Dreadnaught',900,'yes','enforcer-one'),
('Escape Pod','Correllian Engineering Corporation','Transport',10,'no','escape-pod'),
('ETA Starfighter','Kuat Systems Engineering','Starfighter',5,'no','eta-starfighter'),
('Executor','Kuat Drive Yards','Super Weapon',19000,'yes','executor'),
('Fang Fighter','Sorosuub','Starfighter',6,'no','fang-fighter'),
('Far*Reach IV PQR','Loronar Corporation','Survey',80,'no','far-reach-iv-pqr'),
('Firespray','Kuat Systems Engineering','Patrol Ship',21,'no','firespray'),
('Gladiator Destroyer','Rendili StarDrive','Destroyer',600,'no','gladiator-destroyer'),
('Ghost','Correllian Engineering Corporation','Freighter',45,'yes','ghost'),
('Gozanti Cruiser','Correllian Engineering Corporation','Cruiser - Light',64,'no','gozanti-cruiser'),
('GR-45','Gallofree Yards','Transport',60,'no','gr-45'),
('GR-75','Gallofree Yards','Transport',90,'no','gr-75'),
('Guri`s Stinger','Surronian','Assault Ship',1150,'yes','guris-stinger'),
('Hammerhead Cruiser','Rendili StarDrive','Frigate',315,'no','hammerhead-cruiser'),
('Home One','Mon Calmari Shipyards','Cruiser - Heavy',1400,'yes','home-one'),
('Hornet Interceptor','Tenloss Syndicate','Scout Vessel',14,'no','hornet-interceptor'),
('Hosk Station','Alderaan Royal Engineering','Station',200000,'yes','hosk-station'),
('Hounds Tooth','Correllian Engineering Corporation','Freighter',47,'yes','hounds-tooth'),
('HWK-290','Correllian Engineering Corporation','Freighter',17,'no','hwk-290'),
('Hyperspace Marauder','TransGalMeg','Transport',165,'yes','hyperspace-marauder'),
('I-7 Howlrunner','Incom','Starfighter',11,'no','i-7-howlrunner'),
('IG-2000','Trilon','Starfighter',20,'yes','ig-2000'),
('Sith Interdictor Cruiser','Republic Sienar Systems','Destroyer',600,'no','sith-interdictor-cruiser'),
('Interdictor Cruiser','Sienar Fleet Systems','Cruiser - Heavy',1129,'no','interdictor-cruiser'),
('Invisible Hand','Rendili StarDrive','Dreadnaught',1088,'yes','invisible-hand'),
('Ithullian Ore Hauler','Ithullian','Transport',1000,'no','ithullian-ore-hauler'),
('Keldabe','Mandal Motors','Battleship',1000,'No','keldabe'),
('Lady Luck','Sorosuub','Luxury Space Yacht',50,'yes','lady-luck'),
('Lambda Shuttle','Sienar Fleet Systems','Transport',20,'no','lambda-shuttle'),
('Lancer Frigate','Kuat Drive Yards','Frigate',250,'no','lancer-frigate'),
('Lucrehulk Battleship','Hoersch-Kessel','Battleship',3170,'no','lucrehulk-battleship'),
('M22 T Krayt','Mandal Motors','Gunship',50,'no','m22-t-krayt'),
('Marauder Corvette','Republic Fleet Systems','Corvette',195,'no','marauder-corvette'),
('Marauder Starjacker','Byblos Drive Yards','Miner',110,'no','marauder-starjacker'),
('Master Arcas Ship','Hoersch-Kessel','Courier',70,'yes','master-arcas-ship'),
('MC 80B','Mon Calmari Shipyards','Cruiser - Heavy',1200,'No','mc-80b'),
('MC-75','Mon Calmari Shipyards','Cruiser - Heavy',1200,'no','mc75'),
('MC-80','Mon Calmari Shipyards','Cruiser - Heavy',1400,'no','mc-80'),
('Millennium Falcon','Correllian Engineering Corporation','Freighter',34,'yes','millennium-falcon'),
('Miy`til Starfighter','Olanji-Charubah','Starfighter',8,'no','miytil-starfighter'),
('Moldy Crow','Correllian Engineering Corporation','Freighter',17,'yes','moldy-crow'),
('Naboo N1 Starfighter','Theed Palace Space Vessel Engineering Corps','Starfighter',11,'no','naboo-n1-starfighter'),
('Naboo Royal Cruiser','Theed Palace Space Vessel Engineering Corps','Yacht',39,'no','naboo-royal-cruiser'), 
('Naboo Royal Starship','Theed Palace Space Vessel Engineering Corps','Yacht',76,'yes','naboo-royal-starship'),
('Naboo Star Skiff','Theed Palace Space Vessel Engineering Corps','Transport',30,'yes','naboo-star-skiff'),
('Nebula Class Star Destroyer','Republic Engineering Corp','Destroyer',1040,'no','nebula-star-destroyer'),
('Nebulon Ranger','Corellia StarDrive','Courier',25,'yes','nebulon-ranger'),
('Needle Fighter','Loronar Corporation','Starfighter',2.5,'No','needle-fighter'),
('Neimoidian Shuttle','Haor Chall Engineering','Transport',15,'no','neimoidian-shuttle'),
('Nova Class battle cruiser','Olanji-Charubah','Frigate',400,'No','nova-class-battle-cruiser'),
('Nssis Clawcraft','Chiss Ascendancy','Starfighter',7,'no','nssis-clawcraft'),
('Nubian Yacht','Theed Palace Space Vessel Engineering Corps','Yacht',48,'no','nubian-yacht'),
('Outrider','Correllian Engineering Corporation','Freighter',21,'yes','outrider'),
('Profundity','Mon Calmari Shipyards','Cruiser - Heavy',1200,'yes','profundity'),
('Providence Class Star Destroyer','Rendili StarDrive','Dreadnaught',1088,'no','providence-class-sd'),
('Quadjumper','Subpro Corp','Tug',8,'no','quadjumper'),
('Quasar cruiser','Sorosuub','Carrier',340,'no','quasar-cruiser'),
('Razor Crest','unknown','Gunship',30,'yes','razor-crest'),
('Regulator X-Q2','Loronar Corporation','Scout Vessel',150,'No','regulator-x-q2'),
('Resistance Transport','Slayn & Korpil','Transport',16,'no','resistance-transport'),
('Rogue Shadow','Sienar Fleet Systems','Transport',65,'yes','rogue shadow'),
('Sabaoth Destroyer','unknown','Destroyer',300,'no','sabaoth-destroyer'),
('Sabaoth Starfighter','unknown','Starfighter',8,'no','sabaoth-starfighter'),
('Scimitar Assault Bomber','Sienar Fleet Systems','Bomber',14,'no','scimitar-assault-bomber'),
('Sentiel Landing Craft','Cygnus spaceworks','Transport',38,'no','sentiel-landing-craft'),
('ShieldShip','Republic Engineering Corp','Escort Vehicle',500,'no','shieldship'),
('Shree Battle Cruiser','Ssi-Ruuvi','Cruiser - Heavy',900,'no','shree-battle-cruiser'),
('Sith Infiltrator','Republic Sienar Systems','Courier',27,'yes','sith-infiltrator'),
('Skipray Blastboat','Sienar Fleet Systems','Starfighter',25,'no','skipray-blastboat'),
('Slave I','Kuat Systems Engineering','Patrol Ship',21,'yes','slave-i'),
('Slave II','Mandal Motors','Patrol Ship',30,'Yes','slave-ii0'),
('Sorosuub 3000','sorosuub','Yacht',55,'no','sorosuub-3000'),
('Soulless One','Feethan Ottraw Scalable Assemblies','Starfighter',7,'yes','soulless-one'),
('Ssi-Ruuvi Assault Carrier','Ssi-Ruuvi','Carrier',750,'no','ssi-ruuvi-assault-carrier'),
('Ssi-Ruuvi Battle Droid','Ssi-Ruuvi','Starfighter',2,'no','ssi-ruuvi-battle-droid'),
('Ssi-Ruuvi Picket Ship','Ssi-Ruuvi','Patrol Ship',45,'no','ssi-ruuvi-picket-ship'),
('Star Courier','Republic Sienar Systems','Courier',27,'no','star-courier'),
('Star Forge','Rakatan Infinite Empire','Station',3100,'yes','star-forge'),
('Star Home','Olanji-Charubah','luxury Space Yacht',2500,'yes','star-home'),
('Star Jewel','Ubrikkian','Luxury Space Yacht',160,'yes','star-jewel'),
('Starlight Intruder','Mobquet','Transport',113,'yes','starlight-intruder'),
('Stinger Mantis','Latero Spaceworks','Yacht',37,'no','stinger-mantis'),
('Strike Class Medium Cruiser','Loronar Corporation','Cruiser - Medium',450,'no','strike-class-medium-cruiser'),
('Sun Crusher','Galactic Empire','Super Weapon',13,'yes','sun-crusher'),
('Super Star Destroyer','Kuat Drive Yards','Super Weapon',19000,'no','super-star-destroyer'),
('Tantive IV','Correllian Engineering Corporation','corvette',150,'yes','tantive-iv'),
('Tartan Patrol Cruiser','Damorian Manufacturing Corp','Patrol Ship',250,'no','tartan-patrol-cruiser'),
('Taylander Shuttle','Gallofree Yards','Transport',43,'no','taylander-shuttle'),
('Techno Union Starship','Techno Union','Transport',220,'no','techno-union-starship'),
('The Wheel','Bolzi Design','Station',50000,'yes','the-wheel'),
('Theta Class Shuttle','Cygnus spaceworks','Transport',19,'no','theta-class-shuttle'),
('TIE Advanced','Sienar Fleet Systems','Starfighter',11,'no','tie-advanced'),
('TIE Bomber','Sienar Fleet Systems','Bomber',8,'no','tie-bomber'),
('TIE Defender','Sienar Fleet Systems','Starfighter',9,'no','tie-defender'),
('TIE Fighter','Sienar Fleet Systems','Starfighter',6,'no','tie-fighter'),
('TIE Interceptor','Sienar Fleet Systems','Interceptor',11,'no','tie-interceptor'),
('Trade Federation Landing ship','Haor Chall Engineering','Transport',210,'no','trade-federation-landing-ship'),
('Turbulent Class Star Destroyer','Imperial Remnant','Destroyer',1600,'no','turbulent-star-destroyer'),
('U Wing','Incom','Starfighter',24,'no','u-wing'),
('Upsilon Class Shuttle','Sienar-Jaemus Army Systems','Transport',19,'no','upsilon-class-shuttle'),
('V Wing','Kuat Systems Engineering','Starfighter',8,'no','v-wing'),
('VCX 100','Correllian Engineering Corporation','Freighter',44,'no','vcx-100'),
('Venator Star Destroyer','Kuat Drive Yards','Destroyer',1137,'no','venator-star-destroyer'),
('Victory Star Destroyer','Rendili StarDrive','Cruiser - Medium',900,'no','victory-star-destroyer'),
('Virago','Mandal Motors','Starfighter',21,'Yes','virago'),
('Vulture droid','Haor Chall Engineering','Starfighter',7,'no','vulture-droid'),
('Wild Karrde','Correllian Engineering Corporation','Transport',125,'yes','wild-karrde'),
('World Devastator','Galactic Empire','Super Weapon',3200,'no','world-devastator'),
('X Wing','Incom','Starfighter',13,'No','x-wing'),
('Y Wing','Koensayr','Bomber',23,'no','y-wing'),
('Y-4 Raptor','Incom','Transport',28,'no','y-4-raptor'),
('YR-2400','Correllian Engineering Corporation','Freighter',21,'no','yt-2400'),
('YT 1300','Correllian Engineering Corporation','Freighter',34,'no','yt-1300'),
('YV-666','Correllian Engineering Corporation','Freighter',47,'no','yv-666'),
('Z95 Headhunter','Subpro','Starfighter',17,'no','z95-headhunter'),
('Zeta Class Shuttle','Sienar Fleet Systems','Freighter',31,'no','zeta-class-shuttle');

INSERT INTO weapons (name, shipId) VALUES
    ('laser cannons',1),
    ('concussion missiles',1),
    ('none', 2),
    ('turbo lasers',3),
    ('laser cannons',3),
    ('ion cannons',3),
    ('concussion missiles',3),
    ('proton torpedoes',3),
    ('laser cannons',4),
    ('concussion missiles',4),
    ('turbo lasers',5),
    ('laser cannons',5),
    ('ion cannons',5),
    ('tractor beams',5),
    ('mass drivers',5),
    ('turbo lasers',6),
    ('ion cannons',6),
    ('tractor beams',6),
    ('concussion missiles',6),
    ('none',7),
    ('laser cannons',8),
    ('ion cannons',8),
    ('proton torpedos',8),
    ('laser cannons',9),
    ('tractor beams',10),
    ('turbo lasers',11),
    ('laser cannons',11),
    ('ion cannons',11),
    ('tractor beams',11),
    ('proton torpedoes',11),
    ('turbo lasers',12),
    ('ion cannons',12),
    ('tractor beams',12),
    ('laser cannons',13),
    ('turbo lasers',14),
    ('laser cannons',14),
    ('ion cannons',14),
    ('tractor beams',14),
    ('tractor beams',15),
    ('tractor beams',16),
    ('laser cannons',17),
    ('concussion missiles',17),
    ('none',18),
    ('turbo lasers',19),
    ('laser cannons',19),
    ('ion cannons',19),
    ('tractor beams',19),
    ('laser cannons',20),
    ('ion cannons',20),
    ('turbo lasers',21),
    ('laser cannons',21),
    ('laser cannons', 22),
    ('Super laser',23),
    ('turbo lasers',23),
    ('laser cannons',23),
    ('concussion missiles',23),
    ('tractor beams',23),
    ('super laser',24),
    ('turbo lasers',24),
    ('laser cannons',24),
    ('concussion missiles',24),
    ('tractor beams',24),
    ('laser cannons',25),
    ('tractor beams',26),
    ('turbo laser',27),
    ('laser cannons',27),
    ('concussion missiles',27),
    ('tractor beams',27),
    ('laser cannons',28),
    ('proton torpedos',28),
    ('turbo lasers',29),
    ('laser cannons',29),
    ('super laser',30),
    ('turbo lasers',30),
    ('laser cannons',30),
    ('ion cannons',30),
    ('turbo lasers',31),
    ('laser cannons',31),
    ('tractor beams',31),
    ('none',32),
    ('laser cannons',33),
    ('turbo lasers',34),
    ('laser cannons',34),
    ('ion cannons',34),
    ('tractor beams',34),
    ('laser cannons',35),
    ('proton torpedos',35),
    ('laser cannons',36),
    ('laser cannons',37),
    ('concussion missisles',37),
    ('turbo lasers',38),
    ('laser cannons',38),
    ('concussion missiles',38),
    ('laser cannons',39),
    ('laser cannons',40),
    ('none',41),
    ('none',42),
    ('laser cannons',43),
    ('ion cannons',43),
    ('proton torpedoes',43),
    ('turbo lasers',44),
    ('tractor beams',44),
    ('turbo lasers',45),
    ('ion cannons',45),
    ('tractor beams',45),
    ('concussion missiles',45),
    ('laser cannons',46),
    ('turbo lasers',47),
    ('laser cannons',48),
    ('ion cannons',48),
    ('concussion missiles',48),
    ('laser cannons',49),
    ('proton torpedos',49),
    ('laser cannons',50),
    ('laser cannons',51),
    ('laser cannons',52),
    ('concussion missiles',52),
    ('turbo laser',53),
    ('tractor beams',53),
    ('gravity well generators',53),
    ('laser cannons',54),
    ('gravity well generators',54),
    ('turbo lasers',55),
    ('laser cannons',55),
    ('ion cannons',55),
    ('tractor beams',55),
    ('proton torpedoes',55),
    ('turbo lasers',56),
    ('laser cannons',56),
    ('turbo lasers',57),
    ('laser cannons',57),
    ('ion cannons',57),
    ('tractor beams',57),
    ('mass drivers',57),
    ('laser cannons',58),
    ('laser cannons',59),
    ('laser cannons',60),
    ('turbo lasers',61),
    ('laser cannons',61),
    ('laser cannons',62),
    ('ion cannons',62),
    ('concussion missiles',62),
    ('turbo Lasers',63),
    ('tractor beams',63),
    ('plasma drills',64),
    ('none',65),
    ('turbo lasers',66),
    ('ion cannons',66),
    ('turbo lasers',67),
    ('ion cannons',67),
    ('tractor beams',67),
    ('concussion missiles',67),
    ('turbo lasers',68),
    ('ion cannons',68),
    ('tractor beams',68),
    ('concussion missiles',68),
    ('laser cannons',69),
    ('concussion missiles',69),
    ('laser cannons',70),
    ('concussion missiles',70),
    ('laser cannons',71),
    ('proton torpedos',71),
    ('laser cannons',72),
    ('proton torpedos',72),
    ('none',73),
    ('none',74),
    ('laser cannons',75),
    ('turbo lasers',76),
    ('ion cannons',76),
    ('concussion missiles',76),
    ('laser cannons',77),
    ('laser cannons',78),
    ('laser cannons',79),
    ('turbo lasers',80),
    ('ion cannons',80),
    ('laser cannons',81),
    ('none',82),
    ('laser cannons',83),
    ('turbo lasers',84),
    ('ion cannons',84),
    ('tractor beams',84),
    ('concussion missiles',84),
    ('turbo lasers',85),
    ('laser cannons',85),
    ('ion cannons',85),
    ('tractor beams',85),
    ('proton torpedoes',85),
    ('laser cannons',86),
    ('laser cannons',87),
    ('laser cannons',88),
    ('laser cannons',89),
    ('laser cannons',90),
    ('ion cannons',90),
    ('proton torpedoes',90),
    ('none',91),
    ('turbo lasers',92),
    ('laser cannons',92),
    ('laser cannons',93),
    ('laser cannons',94),
    ('concussion missiles',94),
    ('laser cannons',95),
    ('ion cannons',95),
    ('concussion missiles',95),
    ('none',96),
    ('turbo lasers',97),
    ('ion cannons',97),
    ('ion cannons',97),
    ('tractor beams',97),
    ('laser cannons',98),
    ('proton torpedos',98),
    ('laser cannons',99),
    ('ion cannons',99),
    ('proton torpedoes',99),
    ('tractor beam',99),
    ('laser cannons',100),
    ('proton torpedos',100),
    ('concussion missisles',100),
    ('laser cannons',101),
    ('ion cannons',101),
    ('proton torpedoes',101),
    ('laser cannons',102),
    ('laser cannons',103),
    ('ion cannons',104),
    ('tractor beams',104),
    ('laser cannons',105),
    ('turbo lasers',106),
    ('ion cannons',106),
    ('none',107),
    ('turbo lasers',108),
    ('turbo lasers',109),
    ('laser cannons',109),
    ('tractor beams',109),
    ('laser cannons',110),
    ('turbo lasers',111),
    ('none',112),
    ('turbo lasers',113),
    ('ion cannons',113),
    ('tractor beams',113),
    ('concussion missiles',113),
    ('laser cannons',114),
    ('tractor beam',114),
    ('Resonance torpedo',114),
    ('turbo lasers',115),
    ('laser cannons',115),
    ('ion cannons',115),
    ('tractor beams',115),
    ('turbo lasers',116),
    ('laser cannons',116),
    ('laser cannons',117),
    ('none',118),
    ('laser cannons',119),
    ('concussion missiles',119),
    ('turbo lasers',120),
    ('laser cannons',120),
    ('ion cannons',120),
    ('tractor beams',120),
    ('laser cannons',121),
    ('laser cannons',122),
    ('concussion missiles',122),
    ('laser cannons',123),
    ('proton torpedos',123),
    ('laser cannons',124),
    ('ion cannons',124),
    ('concussion missiles',124),
    ('laser cannons',125),
    ('laser cannons',126),
    ('none',127),
    ('turbo lasers',128),
    ('ion cannons',128),
    ('concussion missiles',128),
    ('laser cannons',129),
    ('laser cannons',130),
    ('laser cannons',131),
    ('laser cannons',132),
    ('turbo lasers',133),
    ('laser cannons',133),
    ('tractor beams',133),
    ('concussion missiles',133),
    ('turbo lasers',134),
    ('ion cannons',134),
    ('tractor beams',134),
    ('laser cannons',135),
    ('laser cannons',136),
    ('laser cannons',137),
    ('none',138),
    ('laser cannons',139),
    ('proton torpedos',139),
    ('laser cannons',140),
    ('ion cannons',140),
    ('proton torpedoes',140),
    ('laser cannons',141),
    ('laser cannons',142),
    ('laser cannons',143),
    ('laser cannons',144),
    ('laser cannons',145),
    ('ion cannons',145),
    ('concussion missiles',145),
    ('laser cannons',146);


INSERT INTO affiliations (name) VALUES
    ('Bespin Wing Guard'),
    ('Black Sun'),
    ('bounty hunters'),
    ('Chiss Ascendancy'),
    ('civilian'),
    ('Confederation'),
    ('Corporate Sector Authority'),
    ('First Order'),
    ('Galactic Republic'),
    ('Hapes Consortium'),
    ('Hutt Cartel'),
    ('Imperial'),
    ('Imperial remnant'),
    ('Infinite Empire'),
    ('Ithullian'),
    ('Jedi'),
    ('Mandalorians'),
    ('Naboo'),
    ('New Republic'),
    ('pirates'),
    ('Rebels'),
    ('Resistance'),
    ('Sith'),
    ('Smugglers'),
    ('Ssi-Ruuvi'),
    ('Tennloss Syndicate'),
    ('Zann Consortium'),
    ('Trade Federation');

INSERT INTO ships_affiliations (affiliationId, shipId) VALUES
    (21,1),
    (19,1),
    (12,2),
    (12,3),
    (20,4),
    (27,5),
    (12,6),
    (12,7),
    (21, 8),
    (19,8),
    (16,9),
    (5,9),
    (5,10),
    (10,11),
    (19,11),
    (19,12),
    (1,13),
    (12,14),
    (19,14),
    (6,14),
    (20,14),
    (5,15),
    (16,16),
    (12,17),
    (19,17),
    (16,17),
    (11,17),
    (2,17),
    (20,17),
    (9,18),
    (24,18),
    (19,19),
    (17,20),
    (9,20),
    (9,21),
    (12,21),
    (20,21),
    (5, 21),
    (12,22),
    (12,23),
    (12,24),
    (16,25),
    (6,26),
    (9,27),
    (7,27),
    (12,27),
    (6,27),
    (19,27),
    (11,27),
    (4,27),
    (19,28),
    (24,29),
    (12,30),
    (11,31),
    (5,32),
    (16,33),
    (23,33),
    (9,33),
    (12,33),
    (12,34),
    (17,35),
    (21,35),
    (20,35),
    (12,36),
    (6,37),
    (5,37),
    (12,38),
    (20,38),
    (24,39),
    (12,40),
    (2,40),
    (20,40),
    (5,40),
    (19,41),
    (5,41),
    (5,42),
    (2,43),
    (9,44),
    (19,45),
    (26,46),
    (5,47),
    (3,48),
    (5,49),
    (24,50),
    (12,51),
    (19,51),
    (6,51),
    (3,52),
    (23,53),
    (12,54),
    (6,55),
    (15,56),
    (27,57),
    (17,57),
    (24,58),
    (12,59),
    (12,59),
    (6,61),
    (18,62),
    (11,62),
    (24,62),
    (7,63),
    (20,64),
    (16,65),
    (21, 66),
    (19,66),
    (19,67),
    (19,68),
    (24,69),
    (10,70),
    (6,70),
    (24,71),
    (18,72),
    (18,73),
    (18,74),
    (18,75),
    (19,76),
    (16,77),
    (13,78),
    (6,79),
    (10,80),
    (4,81),
    (13,81),
    (18,82),
    (24,83),
    (19,84),
    (28,85),
    (6,85),
    (5,86),
    (12,87),
    (21,87),
    (20,87),
    (3,88),
    (12,89),
    (21,89),
    (20,89),
    (22,90),
    (16,91),
    (23,91),
    (19,91),
    (12,91),
    (9,92),
    (9,93),
    (12,94),
    (12,95),
    (19,96),
    (25,97),
    (23,98),
    (9,99),
    (12,99),
    (27,99),
    (13,99),
    (20,99),
    (24,99),
    (3,100),
    (3,101),
    (5,102),
    (6,103),
    (16,103),
    (25,104),
    (25,105),
    (25,106),
    (5,107),
    (14,108),
    (23,108),
    (10,109),
    (11,110),
    (24,111),
    (16,112),
    (12,113),
    (12,114),
    (12,115),
    (21,116),
    (27,117),
    (12,117),
    (19,118),
    (5,118),
    (6,119),
    (5,120),
    (9,121),
    (12,121),
    (12,122),
    (12,123),
    (12,124),
    (12,125),
    (12,126),
    (6,127),
    (13,128),
    (19,129),
    (8,130),
    (9,131),
    (19,131),
    (12,131),
    (19,132),
    (5,132),
    (9,133),
    (6,133),
    (12,133),
    (12,134),
    (2,135),
    (6,136),
    (24,137),
    (12,138),
    (21,139),
    (19,139),
    (20,139),
    (21,140),
    (20,140),
    (12,141),
    (5,142),
    (5,143),
    (5,144),
    (21,145),
    (20,145),
    (12,146);

